package au.edu.swin.sdmd.todolist

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import java.time.ZonedDateTime

@Entity
data class ToDo(
    /**
     * We want to make sure that we pass in a value for id or otherwise the Kotlin code will not compile
     * At the same time, we want to make sure that Room actually overrides the value we pass in with its own autogenerated value
     * Setting the default value to 0 achieves both things
     *
     * Source: https://developer.android.com/reference/kotlin/androidx/room/PrimaryKey#autoGenerate()
     */
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val title: String,
    val reminderDateTime: ZonedDateTime?,
    @ColumnInfo(defaultValue = "0") val isCompleted: Boolean = false
)